{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "119e7074-fd35-4ee7-8b0f-a2010b4d5a3f",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import streamlit as st\n",
    "import sys\n",
    "\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=\"Chennai Colleges Chatbot\",\n",
    "    page_icon=\"🏫\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "\n",
    "st.markdown(\"\"\"\n",
    "<style>\n",
    "    .stChatMessage {\n",
    "        padding: 12px;\n",
    "        border-radius: 10px;\n",
    "        margin: 5px 0;\n",
    "    }\n",
    "    .user-message {\n",
    "        background-color: #e3f2fd;\n",
    "        padding: 12px;\n",
    "        border-radius: 10px 10px 0 10px;\n",
    "    }\n",
    "    .bot-message {\n",
    "        background-color: #f5f5f5;\n",
    "        padding: 12px;\n",
    "        border-radius: 10px 10px 10px 0;\n",
    "    }\n",
    "</style>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "\n",
    "st.title(\"🏫 Chennai Colleges Chatbot\")\n",
    "st.markdown(\"Ask me about colleges in Chennai! I have information on 35+ colleges.\")\n",
    "\n",
    "\n",
    "with st.sidebar:\n",
    "    st.header(\"📊 About\")\n",
    "    st.write(\"This chatbot helps you find information about colleges in Chennai.\")\n",
    "    st.write(\"**Features:**\")\n",
    "    st.write(\"• Search by college name\")\n",
    "    st.write(\"• Search by location/area\")\n",
    "    st.write(\"• Get complete college details\")\n",
    "    st.divider()\n",
    "    st.write(\"💡 **Try asking:**\")\n",
    "    st.write(\"- 'Anna University'\")\n",
    "    st.write(\"- 'Colleges in Guindy'\")\n",
    "    st.write(\"- 'SRM Institute'\")\n",
    "    st.write(\"- 'Medical colleges'\")\n",
    "\n",
    "\n",
    "try:\n",
    "    df = pd.read_csv(\"colleges_csvfile.csv\", delimiter=',')\n",
    "    st.sidebar.success(f\"✅ Loaded {len(df)} colleges\")\n",
    "except:\n",
    "    st.error(\"CSV file not found. Please upload 'colleges_csvfile.csv'\")\n",
    "    df = None\n",
    "\n",
    "\n",
    "if \"messages\" not in st.session_state:\n",
    "    st.session_state.messages = [\n",
    "        {\"role\": \"assistant\", \"content\": \"Hi Buddy! I can help you find information about colleges in Chennai. How can I assist you today?\"}\n",
    "    ]\n",
    "\n",
    "\n",
    "for message in st.session_state.messages:\n",
    "    with st.chat_message(message[\"role\"]):\n",
    "        st.markdown(message[\"content\"])\n",
    "\n",
    "\n",
    "import pandas as pd \n",
    "\n",
    "\n",
    "\n",
    "df = pd.read_csv(\"colleges_csvfile.csv\", delimiter = ',')\n",
    "\n",
    "\n",
    "def Chatbot():\n",
    "    print(\"chatbot: Hi Buddy!\")\n",
    "    \n",
    "    while True:\n",
    "        user = input('You: ').lower()\n",
    "\n",
    "        if 'hi' in user or 'hello' in user or 'hey' in user:\n",
    "            print(\"chatbot: Hey there! good to see you here\\nHow are you\")\n",
    "\n",
    "        elif 'am good' in user or 'good' in user or 'fine' in user:\n",
    "            print(\"that's Great\\nI can assist you with providing information about colleges near by you!\\nTo countinue enter -ok-\")\n",
    "\n",
    "        elif 'how are you' in user or \"how r u\" in user:\n",
    "            print(\"Am doing good, Thanks for asking.\\nI can assist you with providing information about colleges near by you!\\nTo countinue enter -ok-\")\n",
    "\n",
    "        elif 'ok' in user or 'okay' in user:\n",
    "            print(\"good to go;\\nenter college name or the Area name to fetch the details!\")\n",
    "\n",
    "        elif 'university of madras' in user or 'chepauk' in user or 'triplicane' in user:\n",
    "            print(\"chatbot: Showing results - University of Madras\\n\",df.iloc[0])\n",
    "\n",
    "        elif 'anna university' in user or 'guindy' in user:\n",
    "            print(\"chatbot: Showing results - Anna University\\n\",df.iloc[1])\n",
    "\n",
    "        elif 'college of engineering' in user or 'guindy' in user:\n",
    "            print(\"chatbot: Showing results - College of Engineering\\n\",df.iloc[2])\n",
    "\n",
    "        elif 'madras christian college' in user or 'mcc' in user or 'east tambaram' in user:\n",
    "            print(\"chatbot: Showing results - Madras Christian College\\n\",df.iloc[3])\n",
    "\n",
    "        elif 'loyola college' in user or 'nungambakkam' in user:\n",
    "            print(\"chatbot: Showing results - Loyola college\\n\",df.iloc[4])\n",
    "\n",
    "        elif 'presidency college' in user or 'chepauk' in user:\n",
    "            print(\"chatbot: Showing results - Presidency college\\n\",df.iloc[5])\n",
    "\n",
    "        elif \"st. joseph's college\" in user or 'cuddalore' in user:\n",
    "            print(\"chatbot: Showing results - St. Joseph's college\\n\",df.iloc[6])\n",
    "\n",
    "        elif \"women's christian college\" in user or 'nungambakkam' in user:\n",
    "            print(\"chatbot: Showing results - Women's Christian college\\n\",df.iloc[7])\n",
    "\n",
    "        elif 'ssn college of engineering' in user or 'kalavakkam' in user:\n",
    "            print(\"chatbot: Showing results - SSN college of engineering\\n\",df.iloc[8])\n",
    "\n",
    "        elif 'sri venkateswara college of engineering (svce)' in user or 'Pennalur' in user or 'Sriperumbadur' in user:\n",
    "            print(\"chatbot: Showing results - Sri Venkateswara college of engineering(svce)\\n\",df.iloc[9])\n",
    "\n",
    "        elif 'srm institute of science and technology (main campus)' in user or 'srm' in user or 'Kattankulathur' in user:\n",
    "            print(\"chatbot: Showing results - SRM institute of science and technology (Main campus)\\n\",df.iloc[10])\n",
    "\n",
    "        elif 'vellore institute of technology (vit chennai)' in user or 'kelambakkam' in user or 'vandalur' in user:\n",
    "            print(\"chatbot: Showing results - Vellore institute of technology (VIT chennai)\\n\",df.iloc[11])\n",
    "\n",
    "        elif 'saveetha engineering college (saveetha university)' in user or 'thandalam' in user:\n",
    "            print(\"chatbot: Showing results - Saveetha engineering college (Saveetha University)\\n\",df.iloc[12])\n",
    "\n",
    "        elif \"rajalakshmi engineering college (rec)\" in user or 'rajalakshmi nagar' in user or 'thandalam' in user:\n",
    "            print(\"chatbot: Showing results - Rajalakshmi engineering college (REC)\\n\",df.iloc[13])\n",
    "\n",
    "        elif 'jeppiaar engineering college (jec)' in user or 'omr' in user or 'rajiv gandhi salai' in user:\n",
    "            print(\"chatbot: Showing results - Jeppiaar engineering college (JEC)\\n\",df.iloc[14])\n",
    "\n",
    "        elif 'chennai institute of technology (cit)' in user or 'kundrathur' in user:\n",
    "            print(\"chatbot: Showing results - Chennai institute of technology (CIT)\\n\",df.iloc[15])\n",
    "\n",
    "        elif 'hindustan institute of technology and science' in user or 'hindustan' in user or 'omr' in user or 'padur' in user:\n",
    "            print(\"chatbot: Showing results - Hindustan institute of technology and science\\n\",df.iloc[16])\n",
    "\n",
    "        elif 'academy of maritime education and training' in user or 'ecr' in user or 'kanathur' in user:\n",
    "            print(\"chatbot: Showing results - Academy of Maritime Education and Training\\n\",df.iloc[17])\n",
    "\n",
    "        elif 'dr. mgr educational and research institute' in user or 'maduravoyil' in user:\n",
    "            print(\"chatbot: Showing results - Dr. MGR Educational and Research Institute\\n\",df.iloc[18])\n",
    "\n",
    "        elif 'b. s. abdur rahman crescent institute of science and technology' in user or 'crescent' in user or 'vandalur' in user:\n",
    "            print(\"chatbot: Showing results - B.S. Abdur Rahman Crescent Institute of science and technology'\\n\",df.iloc[19])\n",
    "\n",
    "        elif 'stanley medical college' in user or 'broadway' in user:\n",
    "            print(\"chatbot: Showing results - Stanley Medical College\\n\",df.iloc[20])\n",
    "\n",
    "        elif 'madras medical college' in user or 'park town' in user:\n",
    "            print(\"chatbot: Showing results - Madras Medical College\\n\",df.iloc[21])\n",
    "\n",
    "        elif 'ethiraj college for women' in user or 'egmore' in user:\n",
    "            print(\"chatbot: Showing results - Ethiraj College for Women\\n\",df.iloc[22])\n",
    "\n",
    "        elif 'dg vaishnav college' in user or 'saidapet' in user:\n",
    "            print(\"chatbot: Showing results - D G Vaishnav College\\n\",df.iloc[23])\n",
    "\n",
    "        elif 'mop vaishnav college for women' in user or 'nungambakkam' in user:\n",
    "            print(\"chatbot: Showing results - MOP Vaishnav College for Women\\n\",df.iloc[24])\n",
    "\n",
    "        elif 'the new college' in user or 'royapettah' in user:\n",
    "            print(\"chatbot: Showing results - The New College\\n\",df.iloc[25])\n",
    "\n",
    "        elif 'vels institute of science' in user or 'pallavaram' in user:\n",
    "            print(\"chatbot: Showing results - Vels Institute of Science\\n\",df.iloc[26])\n",
    "\n",
    "        elif 'sathyabama institute of science and technology' in user or 'omr' in user:\n",
    "            print(\"chatbot: Showing results - University of Madras\\n\",df.iloc[27])\n",
    "\n",
    "        elif 'indian institute of technology madras (iitm)' in user or 'adyar' in user:\n",
    "            print(\"chatbot: Showing results - Indian Institute of Technology Madras (IITM)\\n\",df.iloc[28])\n",
    "\n",
    "        elif 'national institute of fashion technology' in user or 'taramani' in user:\n",
    "            print(\"chatbot: Showing results - National Institute of Fashion Technology\\n\",df.iloc[29])\n",
    "\n",
    "        elif 'srm institute of science and technology' in user or 'ramapuram' in user:\n",
    "            print(\"chatbot: Showing results - SRM Institute of science and Technology\\n\",df.iloc[30])\n",
    "\n",
    "        elif 'a m jain college' in user or 'meenambakkam' in user or 'minambakkam' in user :\n",
    "            print(\"chatbot: Showing results -A M Jain College\\n\",df.iloc[31])\n",
    "\n",
    "        elif 'bharath institute of higher education and research' in user or 'selaiyur' in user:\n",
    "            print(\"chatbot: Showing results - Bharath Institute of Higher Education and Research\\n\",df.iloc[32])\n",
    "\n",
    "        elif 'srm institute of science and technology' in user or 'vadapalani' in user:\n",
    "            print(\"chatbot: Showing results - Srm Institute of Science and Technology\\n\",df.iloc[33])\n",
    "\n",
    "        elif 'madras institue of technology(mit)' in user or 'chrompet' in user:\n",
    "            print(\"chatbot: Showing results - Madras Institue of Technology(MIT)\\n\",df.iloc[34])\n",
    "\n",
    "\n",
    "\n",
    "        else:\n",
    "            print(\"Chatbot: Failed to fetch the results!\\nTry entering other Name or any other Location\")\n",
    "            \n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    Chatbot()\n",
    "\n",
    "if prompt := st.chat_input(\"Type your message here...\"):\n",
    "    \n",
    "    st.session_state.messages.append({\"role\": \"user\", \"content\": prompt})\n",
    "    \n",
    "    \n",
    "    response = chatbot_response(prompt)\n",
    "    \n",
    "    \n",
    "    st.session_state.messages.append({\"role\": \"assistant\", \"content\": response})\n",
    "    \n",
    "    \n",
    "    st.rerun()\n",
    "\n",
    "\n",
    "if st.sidebar.button(\"Clear Chat History\"):\n",
    "    st.session_state.messages = [\n",
    "        {\"role\": \"assistant\", \"content\": \"Hi Buddy! I can help you find information about colleges in Chennai. How can I assist you today?\"}\n",
    "    ]\n",
    "    st.rerun()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
